Fix the scancode ver for macos
fosslight/fosslight_source_scanner pull request #194
Opened 2024-10-14 05:06 UTC by dd-jy

## Description

Fix the scancode ver for macos

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [x] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-10-14 05:19 UTC, soimkim requested changes
잠시 Merge 멈춰주세요.
변경 TO-BE를 찾을께요

2024-10-14 05:33 UTC, soimkim commented on requirements.txt
> -scancode-toolkit>=32.2.0
```
scancode-toolkit==32.0.*;sys_platform=="darwin"
scancode-toolkit==32.2.*;sys_platform!="darwin"
```
@dd-jy , 위와 같이 수정하면 setup.py 수정이 불필요한 것 아닌지 문의드립니다.

2024-10-14 06:58 UTC, dd-jy commented on requirements.txt
> -scancode-toolkit>=32.2.0
@soimkim 
그러네요! 제안주신 방법으로 수정하였습니다.

2024-10-14 06:59 UTC, soimkim approved these changes

2024-10-15 06:15 UTC, soimkim approved these changes

2024-10-18 06:58 UTC, merged